# Change these first
owner: DevMnazz # Your GitHub organization or username, where this repository lives
repo: mnazz-status # The name of this repository

sites:
  - name: Mnazz Panel
    url: https://panel.mnazz.com

status-website:
  baseUrl: /mnazz-status # where "repo" is your repository name
  name: Mnazz Status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
