# Change these first
owner: DevMnazz # Your GitHub organization or username, where this repository lives
repo: mnazz-status # The name of this repository

sites:
  - name: Mnazz Panel
    url: https://panel.mnazz.com
  - name: MnazzMC Wiki
    url: https://mc.mnazz.com

status-website:
  name: Mnazz Status
  cname: status.mnazz.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
